name: Documentation

on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Publish ${{ matrix.docs.product }}
    runs-on: ubuntu-latest
    strategy:
      # We need to checkout and publish to another branch,
      # to avoid conflicts, run everything in serial mode.
      max-parallel: 1
      matrix:
        docs:
          - product: MonkiProjectsDTO
            target-folder: monki-projects-dto
          - product: MonkiMapDTO
            target-folder: monki-map-dto
    steps:
      - uses: actions/checkout@v2
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          base-url: /monki-projects-dto-swift/${{ matrix.docs.target-folder }}
          format: html
          inputs: Sources/${{ matrix.docs.product }}
          module-name: ${{ matrix.docs.product }}
          output: Documentation
      - name: Update Permissions
        run: 'sudo chown --recursive $USER Documentation'
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          token: ${{ secrets.SWIFT_DOC_ACCESS_TOKEN }}
          branch: gh-pages
          folder: Documentation
          target-folder: ${{ matrix.docs.target-folder }}
